name: call_and_response
description: Spin up a fake HTTP Server with Dart
version: 1.0.0
repository: https://github.com/MelbourneDeveloper/call_and_response

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0

dev_dependencies:
  build_runner: ^2.3.3
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
